## 1
name: Test and deploy

on:
  push:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: adamkdean/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        with:
          text: "Hello simple notification"